### ISSUE TITLE
WebVR doesn't work correctly in some sites with e10s enabled

### ISSUE THREAD

**Issue by MortimerGoro** [MozillaReality/FirefoxReality#1048]
## Hardware

All

## Steps to Reproduce

1. Load https://chromatic.funktroniclabs.com/
2. Enter VR

## Current Behavior

- I can enter WebVR but the animation is paused after a while. It doesn't look like a blocked frame, because there isn't any reprojection. It seems like the web is always rendering the same frame.
- Demo works correctly in WebGL if you click "try without a headset"
- WebVR animation works correctly whit e10s disabled

## Expected Behavior

- Animation should work with e10s enabled

## Possible Solution

Research required

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by cvan** [comment]
Will investigate and provide logs. Thanks for filing.

**Comment by philip-lamb** [comment]
Pushing to 1.3 as we won't have time to test e10s thoroughly for 1.2.

**Comment by jvonitter** [comment]
We think this is fixed by other work. Needs testing.

**Comment by philip-lamb** [comment]
Tested on Oculus Go with 1.2.3 and still an issue. Needs further investigation.

**Comment by philip-lamb** [comment]
@kearwood Please take a look at this issue and let me know if you can identify the problem and a fix.

**Comment by kearwood** [comment]
Okay!  Investigating now

**Comment by kearwood** [comment]
I have managed to reproduce this with local GeckoView builds on an Oculus Go.

It definitely appears to be pumping RAF loops and appears to be getting new VRFrameData updates.

I suspect that the affected sites may differ from others in that they are using a different timestamp to drive the animations.

Is it possible that this site is using VRFrameData.timestamp while others are using the timestamp passed into the RAF callback?  (Or vise-versa?)

If we see no progression of either timestamp value with e10s enabled, this could help further isolate the cause.

**Comment by bluemarvin** [comment]
This is still blocked by Gecko. The current Gecko WebVR Android implementation is broken. The current implementation expects the external vr struct to be present in the content process. Since on android it is not allocated from shared memory it is not present in the content process. This prevents the refresh driver from knowing the content is presenting and thus RaFs do not get ticked since the refresh driver stalls waiting for paints that will not occur. I have filed a bugzilla issue here: https://bugzilla.mozilla.org/show_bug.cgi?id=1578851

**Comment by daoshengmu** [comment]
> I have managed to reproduce this with local GeckoView builds on an Oculus Go.
> 
> It definitely appears to be pumping RAF loops and appears to be getting new VRFrameData updates.
> 
> I suspect that the affected sites may differ from others in that they are using a different timestamp to drive the animations.
> 
> Is it possible that this site is using VRFrameData.timestamp while others are using the timestamp passed into the RAF callback? (Or vise-versa?)
> 
> If we see no progression of either timestamp value with e10s enabled, this could help further isolate the cause.

The timestamp of VRFrameData will be increased in e10s mode, and this issue can't be reproduced in Windows WebVR. I am thinking if we did improper things in Android only.

**Comment by jvonitter** [comment]
need by #451

**Comment by Softvision-GeluHaiduc** [comment]
I will remove the QA label for now as there is nothing actionable by QA.
If QA attention is needed in the future please add the label again and we will address it.

**Comment by philip-lamb** [comment]
Patch is done by blocked waiting on review.

**Comment by daoshengmu** [comment]
It should be resolved by https://bugzilla.mozilla.org/show_bug.cgi?id=1586110.

**Comment by daoshengmu** [comment]
I have confirmed it works by https://bugzilla.mozilla.org/show_bug.cgi?id=1586110.
