### ISSUE TITLE
"open in new window" button doesn't work correctly

### ISSUE THREAD

**Issue by jvonitter** [MozillaReality/FirefoxReality#1469]
## Hardware
Quest + apk from 7/23/19

## Steps to Reproduce
1. On the content feed, press and hold over one of the video tiles.

## Current Behavior
1) Sometimes, the button doesn't come up, but instead the page moves instead
2) If the button does come up, hovering over it makes the button flicker between the selection color to normal color
3) Clicking away from the button doesn't make it go away
4) Hovering over the button also triggers hover over the tiles below it (and sometimes tiles further to the right)
5) Sometimes the button gets stuck and cant be clicked or dismissed. I had to restart the app to make it go away.
6) When the button is up and I try to click, sometimes the button text moves as though I'm dragging it. (I think the whole button may be moving but the top and bottom are cut off so it looks like just the text is.)
7) I have to try many times to actually click the button.

## Expected Behavior
1) Moving a very small bit (ie normal hand jitter / only a few pixels) shouldn't be interpreted as scrolling
2-7) The button should appear when I long-press, display the hover state when I hover and accept a click on the first try. It should not affect the page beneath it at all and should not move. When I click, the button should disappear (both if I clicked on it or anywhere else).

```
```

</details>

**Comment by keianhzo** [comment]
@jvo I've made some adjustments to the context menu and the above should be fixed. Sharing an APK here. It's already in the multi-window branch.

https://send.firefox.com/download/efbc8ac13da2747f/#_K-vFxQpKY3RopaYU_KPXg

**Comment by keianhzo** [comment]
Pinging @jvonitter  for testing as I added the wrong person in my last comment.

**Comment by jvonitter** [comment]
It is way better! #6 above is still happening though. I tried to get a movie of it but Oculus isn't cooperating. 
There's some placement weirdness too, but I think that's a design issue so I'll check in with Nadja about it and make a new ticket if needed.

**Comment by keianhzo** [comment]
@jvonitter Is #6 happening in curved mode o also in flat?

**Comment by jvonitter** [comment]
I saw it in flat mode. Will check curved when I get a chance

**Comment by keianhzo** [comment]
@jvonitter I've been trying to reproduce this but I can't really see # 6 happening. What I've been able to reproduce it that the popup is sometimes not visible in curved mode. @mortimergoro I wonder if this might be related to #1468. If you try to open the context menu clicking on a link in the extremes of the left/right windows in curved mode you can appreciate it.

**Comment by MortimerGoro** [comment]
@keianhzo yes, that's related to #1468. I can also reproduce it with the movable keyboard.

**Comment by keianhzo** [comment]
Closing this, it should have been closed by #1676 but it didn't
