### ISSUE TITLE
[HTC] The "English[en]" language is wrongly set as default for the Preferred Website Language when it's Reset

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2422]
**[Notes]:**
- As a side effect as this issue the "English (United States)[en-US]" language can no longer be set as default since it appears to already be checked.

**[Affected Versions]:**
-  Firefox Reality version 7 RC6 (b01367aa)

**[Affected Platforms]:**
- HTC Vive Focus Plus - Android 7.1.2
- HTC Vive Focus - Android 7.1.2

**[Prerequisites]:**
- The Firefox Reality browser is opened.

**[Steps to reproduce]:**
1. Open the "Language" card from Settings.
2. Click the "Edit" button for the "Display Website Language" option.
3. Click the "Reset" button from the bottom of the card.
4. Observe the Preferred Website Language section.

**[Expected results]:**
- The "English (United States)[en-US]" language remains set as default.

**[Actual results]:**
- The "English[en]" language is set as default.

**[Additional Notes]:**
- This issue is reproducible if any language is set as Preferred Website Language.
- This issue is also reproducible if the "Reset" button from the "Language" card is clicked.
- I was not able to reproduce this issue on the Oculus devices.
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1nl0fLwLuXKUP4HGHFDBnsK9bZdMIv5Mf).

**Comment by keianhzo** [comment]
Fixed by https://github.com/MozillaReality/FirefoxReality/pull/2425/commits/2bd532442b259423dad17bbfde209b3b77b1db9e

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue with the latest Firefox Reality version 8-33472001 (6ba38814) installed on the HTC Vive Focus and Focus Plus headsets.
Unfortunately, the issue is still reproducible. I will reopen the issue.

**Comment by Softvision-RemusDranca** [comment]
Based on [comment](https://github.com/MozillaReality/FirefoxReality/pull/2518#issuecomment-569695793) from the PR the expected behavior is now the one described in this issue where the system language is set as default content language after reset. Also the "English (United States)[en-US]" language is no longer checked and can be added in the Preferred Language section.
Tested on the HTC Vive Focus Plus (Android 7.1.2) and HTC Vive Focus (Android 7.1.2) with the latest Firefox Reality version 8-40030225 (e6f4ddab) from master.
I will mark this issue as verified-fixed.
