### ISSUE TITLE
The “Autoplay Media” setting is not respected on all websites

### ISSUE THREAD

**Issue by heres-maria-sv-inactive** [MozillaReality/FirefoxReality#2485]
**[Affected Versions]:**
- Firefox Reality version 8-33472001 (6ba38814)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- Oculus Go (Android 7.1.2)
- HTC Vive Focus Plus - Android 7.1.2
- HTC Vive Focus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.
- The “Autoplay Media” setting is turned off.

**[Steps to reproduce]:**
1. Navigate to a video page that is not on YouTube (e.g. https://www.twitch.tv/videos/522251398).
2. Observe the video.

**[Expected results]:**
- The video doesn’t automatically start playing.

**[Actual results]:**
- The video automatically starts playing.

**[Notes]:**
- This issue is reproducible on multiple websites (e.g. Twitch, Vimeo, Dailymotion).
- There are websites where, if “Autoplay Media” is turned on, videos will not automatically start playing (e.g. Veoh).
- This issue is also reproducible for audio only (e.g. [this](http://freakonomics.com/podcast/hate-taxes-less/) will not automatically start playing.)
- This issue is not reproducible on YouTube.
- Attached is a recording of the [issue](https://drive.google.com/open?id=19QBMR88La4jvXmGw4dkae87rWVoDJ7vf).

**Comment by keianhzo** [comment]
Related GV issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1577596

**Comment by jvonitter** [comment]
We shouldnt make the settings more granular at this point - just all on/off like we currently have.

**Comment by keianhzo** [comment]
That Bugzilla bug will also expose a way to change the autoplay default level so we are able to just block all autoplay which we can't do now with the currently available GV API. @bluemarvin correct me if I'm wrong but I think this is the patch we are waiting for to fix this issue.

**Comment by jvonitter** [comment]
looks like the bugzilla bug is fixed, so we can do our bit now. unblocked!

**Comment by bluemarvin** [comment]
GeckoView add two new permissions:
```
        /**
         * Permission for allowing autoplay of inaudible (silent) video.
         */
        int PERMISSION_AUTOPLAY_INAUDIBLE = 4;

        /**
         * Permission for allowing autoplay of audible video.
         */
        int PERMISSION_AUTOPLAY_AUDIBLE = 5;
```

**Comment by heres-maria** [comment]
This issue is still reproducible as initially described on the latest Firefox Reality version 8 RC1 build (7a444d0c). 
Tested on Oculus Go (Android 7.1.2), Oculus Quest (Android 7.1.1), HTC Vive Focus Plus (Android 7.1.2) and HTC Vive Focus (Android 7.1.2).

**Comment by bluemarvin** [comment]
My understanding is that the current behavior matches desktop from comment: https://github.com/MozillaReality/FirefoxReality/pull/2624#pullrequestreview-342509562

**Comment by heres-maria** [comment]
@bluemarvin I looked into this a bit more. 
While this behavior matches the one encountered on Firefox Release 72.0.1, it does not match the one on Firefox Nightly 74.0a1, where videos do not automatically start playing on either YouTube or Vimeo when the Autoplay setting is set to Block Audio and Video. 
This issue is also not reproducible on Firefox Preview Nightly when using the steps outlined in [this comment](https://github.com/mozilla-mobile/fenix/issues/5636#issuecomment-536818974), which describes a workaround for a similar issue on Fenix.

**Comment by bluemarvin** [comment]
GeckoView currently doesn't support  setting the value to BLOCKING_ALL

**Comment by bluemarvin** [comment]
This will require some follow up with gecko media team. Moving to v10.

**Comment by bluemarvin** [comment]
Probably won't be addressed in time for v10
