### ISSUE TITLE
[L10n] The "Sync Now" button's name from the "Manage Account" prompt is cut off

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2529]
**[Affected Versions]:**
- Firefox Reality version 8-33550026 (933fcd51)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.
- The app's language is set in "Francais".
- You are logged into an FxA account and the account is synced.

**[Steps to reproduce]:**
1. Click the Settings button.
2. Click the "Manage Account" card.
3. Observe the "Sync Now" button.

**[Expected results]:**
- The button is correctly displayed.

**[Actual results]:**
- The name of the button is cut off.

**[Additional Notes]:**
- The locales on which this issue is reproducible are: DE, FR, IT and RU.
- Attached is a screenshot of the issue:
![Manage Account Synced](https://user-images.githubusercontent.com/40061643/71366759-a79de680-25ab-11ea-8dc4-cf889dca9fbc.png)

**Comment by jvonitter** [comment]
@keianhzo looks like we'd be ok if the button grew a little here, but not if it's a crazy amount of special-casing.

**Comment by keianhzo** [comment]
@jvonitter I've made the button wider although I can see this happening again with future languages as long as we have fixed sizes.

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible with the latest Firefox Reality version 8 RC1 (7a444d0). 
However, this issue is still reproducible with the French language for which I opened issue #2652 for tracking purpose having a lower severity.
Tested on Oculus Go (Android 7.1.2), Oculus Quest (Android 7.1.1), HTC Vive Focus Plus (Android 7.1.2) and HTC Vive Focus (Android 7.1.2).
