### ISSUE TITLE
The YouTube homepage noticeably displays a different layout while loading

### ISSUE THREAD

**Issue by heres-maria** [MozillaReality/FirefoxReality#2558]
**[Affected Versions]:**

- Firefox Reality version 8-33611921 (67403bf2)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is open.

**[Steps to reproduce]:**                                        
1. Go to the [YouTube homepage](https://www.youtube.com/).
2. Observe the layout as it loads.

**[Expected results]:**
-  The layout displayed at the start of the loading process is the same as the final one.

**[Actual results]:**
- While loading, the layout is different from the final layout.

**[Notes]:**
- This is reproducible for all window sizes and the intermediary layout is the same for all of them, displaying three videos in a line.
- Needed by #1760.
- Attached is a recording of the [issue](https://drive.google.com/file/d/1p8MNhh4PBouxTLRPuF_Td7PONAk5gtaK/view?usp=sharing).

**Comment by jvonitter** [comment]
@MortimerGoro anything we can do about this?

**Comment by MortimerGoro** [comment]
This has been improved in  #2617

**Comment by MortimerGoro** [comment]
fixed in #2617

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible on windows having the 3x, 2x and 1x size.
However, this issue is still reproducible on windows having the 0.5x size.
Tested on Oculus Go (Android 7.1.2), Oculus Quest (Android 7.1.1), HTC Vive Focus Plus (Android 7.1.2) and HTC Vive Focus (Android 7.1.2) using the latest Firefox Reality version 8-40101959 (3c2a71e2). 

Considering this I will reopen this issue.

**Comment by heres-maria** [comment]
I have verified this issue and it is no longer reproducible with the latest Firefox Reality version 8 RC1 build (7a444d0c). The 0.5x windows now display the proper layout while loading.
Tested on Oculus Go (Android 7.1.2), Oculus Quest (Android 7.1.1), HTC Vive Focus Plus (Android 7.1.2) and HTC Vive Focus (Android 7.1.2).
