### ISSUE TITLE
Dismissing the Bookmarks/History/PB views using the controller/CLEAR doesn’t return the buttons’ icons to the normal size

### ISSUE THREAD

**Issue by heres-maria** [MozillaReality/FirefoxReality#2782]
**[Affected Versions]:**
- Firefox Reality version 9-40432159 (37ab021b)
- Firefox Reality 8.1 (a0fcc8a3)
- Firefox Reality 8 rc5 (ad776185)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on, the browser is installed and open.

**[Steps to reproduce]:**                                        
1. Click the “Open History” button from the tray.
2. Press the back button on the controller to dismiss the “History” view.
3. Observe the “Open History” button.

**[Expected results]:**
- The icon of the button has returned to its normal (100%) size.

**[Actual results]:**
- The icon of the button is still enlarged (125%).

**[Notes]:**
- This issue is also reproducible for the PB button when using the “CLEAR” button.
- This issue is reproducible in production.
- This issue is not reproducible when dismissing them by clicking on the tray buttons.
- Attached is a [recording](https://drive.google.com/file/d/1xdgHbe7KrDdJVUiw6SqspWqLfeeHmsL9/view?usp=sharing) of the issue.

**Comment by keianhzo** [comment]
@bluemarvin This has already been fixed in a PR but that PR includes a refactor and I don't think we want to introduce more uncertainty at this point so I'm moving this to v10.

**Comment by Softvision-GeluHaiduc** [comment]
I have verified this issue with the latest Firefox Reality version 10-140780019 (93eff892) installed on the Oculus Go, HTC Vive Focus Plus and Pico Neo2 headsets.
Unfortunately the issue is still present on the Pico Neo2 headset and on the other headsets the issue is still reproducible for the PB button from the menu tray.

**Comment by Softvision-GeluHaiduc** [comment]
I have verified this issue with the latest Firefox Reality version 11-141770117 - 68128fbe installed on the Oculus Go, HTC Vive Focus Plus, Pico Neo2 and Pico G2 4K headsets.
Now, dismissing the Bookmarks/History/Downloads/PB views using the controller/CLEAR returns the buttons icons to the normal size.
