### ISSUE TITLE
The default values displayed in the input fields from the Display card are not unfocused when clicking inside the input field

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2859]
**[Affected Versions]:**
- Firefox Reality 9 RC3 (18aba8b)

**[Affected Platforms]:**
- HTC Vive Focus Plus - Android 7.1.2
- Oculus Quest - Android 7.1.1
- Pico Neo 2 - Android - 8.1.0

**[Prerequisites]:**
- The headset is turned on and the app is opened.

**[Steps to reproduce]:**										
1. Open the Display card from Settings.
2. Click the "Edit" button for the "Homepage" option.
3. Click inside the displayed input field.
4. Observe the behavior.

**[Expected results]:**
- The value inside is no longer highlighted and the caret is displayed.

**[Actual results]:**
- The value remains highlighted and the text caret is not displayed.

**[Notes]:**
- This issue is also reproducible with the input fields for the "Display Density" and "Display DPI" options.
- This issue is not reproducible when editing the options a second time, while having different values.
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1ioLyYn7aJJba5ZsXtlogCnupAA3ZMl11).

**Comment by keianhzo** [comment]
@Softvision-RemusDranca I think this is already fixed.

**Comment by Softvision-RemusDranca** [comment]
@keianhzo I've retested this issue and it's still reproducible with the Firefox Reality version 10 RC4 (2999129). The default strings remain highlighted when clicking inside the input field.

Tested on HTC Vive Focus (Android 7.1.2), Oculus Quest (Android 7.1.1), and Pico Neo 2 (Android - 8.1.0) devices.

**Comment by keianhzo** [comment]
@Softvision-RemusDranca For what I understand form the original UIS-16 Settings_016.pdf, the text is by default selected when editing but I agree it's weird so maybe it's time to change it.

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 11-141492311 (a9b58ee6) installed on the Oculus Go, Pico Neo2 and Pico G2 4K headsets.
Now, the default values displayed in the input fields from the Display card are unfocused when clicking inside the input field and the text caret is displayed at the end of the string.
