### ISSUE TITLE
[Pico] [Intermittent] Sometimes the window is not resized if manually resized from the corners

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#2862]
**[Affected Versions]:**
- Firefox Reality version 9 RC3 (18aba8be)

**[Affected Platforms]:**
- Pico Neo2 - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is opened.

**[Steps to reproduce]:**
1. Click the resize button from the hamburger menu.
2. Using the controller resize the window vertically and horizontally multiple times.
3. Using the controller resize the window manually from the corner.
4. Observe the behaviour.

**[Expected results]:**
- The window is resized accordingly.

**[Actual results]:**
- The window is not resized.

**[Notes]:**
- Attached a screen recording of the issue [here](https://drive.google.com/open?id=1RpKWVMVT_qK0ANLJhIj0uGBWByF37Mk5).

**Comment by bluemarvin** [comment]
I can reproduce this on all platforms.

**Comment by Softvision-GeluHaiduc** [comment]
I tried to reproduce this issue with the latest master Firefox Reality version 10-40760940 (2516a84d) installed on the Oculus Go, HTC Vive Focus Plus and Pico Neo2 headsets but didn't manage to.

**Comment by keianhzo** [comment]
I've been trying for a while and I couldn't really reproduce this. Is this still an issue @Softvision-GeluHaiduc?

**Comment by bluemarvin** [comment]
> I've been trying for a while and I couldn't really reproduce this. Is this still an issue @Softvision-GeluHaiduc?

I doubt this has been fixed. When I looked at it you had to move fast enough that you release the click outside of the drag handles.

**Comment by Softvision-GeluHaiduc** [comment]
@keianhzo I tried reproducing the issue with the latest build and the issue is still reproducible, however the outcome is a bit different, [here](https://drive.google.com/file/d/1iH-DpX301QG_UlLszk-vOrOsJ6PwrhUe/view?usp=sharing) is a recording, the screen isn’t resized accordingly.
