### ISSUE TITLE
The username from saved logins remains underlined with red after being edited

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#3783]
**[Affected Versions]:**
- Firefox Reality version 12 RC1 (cc3eab03)

**[Affected Platforms]:**
- HTC Vive Focus Plus - Android 7.1.2
- Pico G2 4K - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.
- Make sure to have the settings menu open.

**[Steps to reproduce]:**
1. Click the "Saved logins..." button from the "Logins And Passwords" card.
2. Click on one of the entries from the list.
3. Edit the username.
4. Click the "Save" button and observe the username.

**[Expected results]:**
- The new username is saved.

**[Actual results]:**
- The new username remains underlined with red after being saved.

**[Notes]:**
- After reentering the saved login the username is no longer underlined.
- Attached a screen recording of the issue [here](https://drive.google.com/file/d/10tcyRlJ_SOf1mAMgUHxQpkn_f9aryr4X/view?usp=sharing).

**Comment by keianhzo** [comment]
This should be fixed in the latest RC.

**Comment by Softvision-RemusDranca** [comment]
I've retested this issue and it's still reproducible using the Firefox Reality v12 RC4 (9fd870c). It seems to be mostly reproducible for the user names that have special characters, punctuation marks in the string (ex: "example.test002@gmail.com").

Tested on HTC Vive Focus (Android 7.1.2) and Pico Neo2 (Android 8.1.0).

Considering this, I will reopen this issue.

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible using the Firefox Reality v12 RC5 (864a696). The user name is no longer underlined when editing and also after saving the changes.

Tested on Oculus Quest (Android 7.1.1), HTC Vive Focus (Android 7.1.2) and Pico Neo2 (Android 8.1.0).
