### ISSUE TITLE
Browser locale is always 'en-US'; system locale is not respected

### ISSUE THREAD

**Issue by cvan** [MozillaReality/FirefoxReality#786]
## Hardware
- Oculus Go
    - Firefox Reality
        - master (76881bd)
        - PR #728 (fc07726)
- iPhone 7
    - iOS 11

## Steps to Reproduce
1. Change the language to _German_ on your mobile phone with which you used to install the Oculus companion app.
2. Do a _Factory Reset_ of the Oculus Go (from holding both the Power and Volume-Down buttons).
3. Launch http://www.reliply.org/tools/requestheaders.php in **Oculus Browser**.
4. Take notice of the **`Accept-Language`** HTTP request header that the browser sent to the server for the `GET` request of that page.
5. Launch http://www.reliply.org/tools/requestheaders.php in **Firefox Reality**.
6. Take notice of the **`Accept-Language`** HTTP request header that the browser sent to the server for the `GET` request of that page.

## Current Behavior
The system locale is not respected.

- Firefox Reality always sends this HTTP request header: `Accept-Language: en-US,en;q=0.5`
- `navigator.language` is `"en-US"`
- `navigator.languages` is `["en-US", "en"]`

![image](https://user-images.githubusercontent.com/203725/48768113-53c51d80-ec86-11e8-8493-fd7b70c8ef62.png)

## Expected Behavior
- Firefox Reality should sends this HTTP request header: `Accept-Language: de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7` (or one with similar [`q` weights](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language#Directives), but with the same locale/language in that order)
- `navigator.language` is `"de-DE"`
- `navigator.languages` is `["de-DE", "de", "en-US", "en"]`

![image](https://user-images.githubusercontent.com/203725/48768117-56c00e00-ec86-11e8-8418-428ce964f34a.png)

## Context

I discovered this bug while testing Firefox Reality in German for PR #634.

**Comment by cvan** [comment]
@mbrubeck Very excellent! Thank you for pointing me to the correct bug to track.

@MozillaReality/fxr-eng: FYI: For now, it sounds like we'll keep the Settings for Voice Search Language separate. And we can add a separate Settings for Language later (for webpage content - i.e., `Accept-Language`/`navigator.language`). Issue #794 will cover the addition of `Content Language` to the `Settings > Language` pane (à la Firefox's `Settings > Language`).

**Comment by philip-lamb** [comment]
@cvan bugzilla notes this as fixed in Gecko 66, and FxR master is now on Geckoview 67. Can you test against master and update this bug?

**Comment by cvan** [comment]
On an Oculus Go, I switched my phone's system Language to **Spanish**, did a factory reset on the headset, reinstalled, and launched FxR.

FxR's application UI + menu text - all correctly set in **Spanish**. But it appears still the request headers and the JS APIs are returning **English**.

```
>> navigator.language
"en-US"
>> navigator.languages
["en-US", "en"]
```

**Comment by cvan** [comment]
Still appears blocked. See my comment above: https://github.com/MozillaReality/FirefoxReality/issues/786#issuecomment-482082789

I could be doing something wrong (I hope I am). Can we confirm on GV these (`Accept-Language`, `navigator.language`, `navigator.languages`) are all getting set correctly as expected?

**Comment by cvan** [comment]
I can confirm this still happens. I did another Oculus Factory Reset setting my language to Chinese (Traditional) (`zh-CN`).

Oculus Browser properly sets `navigator.language`, `navigator.languages`, and `Accept-Language`.

![image](https://user-images.githubusercontent.com/203725/57050321-a5180680-6c41-11e9-92f9-58f25615707d.png)

FxR / GV still does not:

![image](https://user-images.githubusercontent.com/203725/57050334-b3662280-6c41-11e9-98d9-95340476dde4.png)

<hr>

cc @mbrubeck / @bluemarvin (re: GV [bug 1496190](https://bugzilla.mozilla.org/show_bug.cgi?id=1496190)) + @MortimerGoro (re: PR #1116)

**Comment by cvan** [comment]
FYI: The latest GeckoView bug tracking it is here, and the latest update: https://bugzilla.mozilla.org/show_bug.cgi?id=1543823#c6

Will retest when the patch lands.

**Comment by philip-lamb** [comment]
Won't be in time for v1.2. Bumping.

**Comment by cvan** [comment]
Tested this this morning. Patch still hadn't landed. Checked just now. It landed three hours ago: https://hg.mozilla.org/integration/autoland/rev/357afb475968

I will update GeckoView locally and test.

**Comment by philip-lamb** [comment]
I saw it land but I think it got backed out for test failure.

**Comment by cvan** [comment]
done in PR #1237
