### ISSUE TITLE
 360 YouTube videos do not work when embedded using iframe.

### ISSUE THREAD

**Issue by caseyyee** [MozillaReality/FirefoxReality#870]
## Hardware
Go
1.1

## Steps to Reproduce
1. Some sites examples with embedded YouTube 360 videos:
http://prosperxr.com/vrportfolio#gameover
https://www.leliomoehr.com/360-vr

2. Click "Watch"

## Current Behavior
360 video plays back with 2D pan controls and will not display correctly in VR modes.

## Expected Behavior
YouTube should play back in unwrapped 360 video that will work with VR video modes.

## Possible Solution
My guess is that the iframe'd YouTube is not seeing customized UA string that plays the video back in unwrapped 360 player.

**Comment by bluemarvin** [comment]
This is probably due to a limitation of the UA override code in GeckoView since it only overrides the UA for the root content window.

**Comment by cvan** [comment]
Will be solved by https://bugzilla.mozilla.org/show_bug.cgi?id=1511281

**Comment by philip-lamb** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1511281 is resolved fixed. @cvan please test.

**Comment by philip-lamb** [comment]
Into 1.x as we have a supported path on youtube for now which involves an extra click to break out of the youtube embedded player.

**Comment by cvan** [comment]
I can still reproduced this:

- http://prosperxr.com/vrportfolio#gameover
- https://www.leliomoehr.com/360-vr

I haven't investigated too much further, but the embedded `<iframe>` will always need to include `allowfullscreen` (also `allow="autoplay; encrypted-media"`):

```html
<!-- 2D -->
<iframe width="560" height="315" src="https://www.youtube.com/embed/videoseries?list=PLx0sYbCqOb8TBPRdmBHs5Iftvv9TPboYG" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>

<!-- 360 -->
<iframe width="560" height="315" src="https://www.youtube.com/watch?v=JL6NAIVpl54&mozVideoProjection=360_auto" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>

<!-- 2D (no cookies) -->
<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/videoseries?list=PLx0sYbCqOb8TBPRdmBHs5Iftvv9TPboYG" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>

<!-- 360 (no cookies)
<iframe width="560" height="315" src="https://www.youtube-nocookie.com/watch?v=JL6NAIVpl54&mozVideoProjection=360_auto" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
```

To fix this, this will likely require changes to the [YouTube Web Extension content script](https://github.com/MozillaReality/FirefoxReality/blob/0dfb62e/app/src/main/assets/web_extensions/youtube_webcompat/main.js) to not filter on `/watch` URLs, and to wait for the player to load within the `<iframe>`. Will probably need to listen for some YouTube-specific events and `window.onmessage` (and likely need to `postMessage` back and forth).

Also, try modifying in the [`manifest.json` file, the `run_at` key](https://github.com/MozillaReality/FirefoxReality/blob/0dfb62e/app/src/main/assets/web_extensions/youtube_webcompat/manifest.json#L18) to be `"document_idle"` or  `"document_end"`.

And, for reference: in the [`manifest.json` file, the `all_frames` key](https://github.com/MozillaReality/FirefoxReality/blob/0dfb62e/app/src/main/assets/web_extensions/youtube_webcompat/manifest.json#L19) when `true` applies to all frames/`<iframe>`s that are not the document's parent window, and `false` applies such that the content script is injected for only the document's parent window.

**Comment by Softvision-GeluHaiduc** [comment]
I will remove the QA label for now as there is nothing actionable by QA.
If QA attention is needed in the future please add the label again and we will address it.
